version: '3.8'

services:

  postgres_sample:
    container_name: postgres-sample-kotlin
    image: postgres:12-alpine
    ports:
      - '5431:5431'
    command: -p 5431
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample
      POSTGRES_DB: sample
      PGDATA: /var/lib/postgresql/data/sample/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sample" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus_sample:
    container_name: prometheus-sample
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    restart: always
    networks:
      - "sample-network"

  grafana_sample:
    container_name: grafana-sample
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana/sample
    networks:
      - "sample-network"

volumes:
  dbdata:
    driver: local
  prometheus_data: {}
  grafana_data: {}

networks:
  sample-network:
    driver: bridge